### ISSUE TITLE
phantomjs hangs (Windows 8.1)

### ISSUE THREAD

**Issue by asunar** [TestArmada/boilerplate-nightwatch#3]
$> "./node_modules/.bin/magellan" --browser=phantomjs
Sauce configuration OK
Magellan-nightwatch test iterator found nightwatch configuration at: ./conf/nightwatch.json

Running 3 tests with 3 workers with phantomjs

--> Worker 1, mock port: 12000, running test: tests/github.js @phantomjs
--> Worker 3, mock port: 12006, running test: tests/walmart-shirt.js @phantomjs
--> Worker 2, mock port: 12003, running test: tests/walmart-book.js @phantomjs

hangs...

**Comment by geekdave** [comment]
Thanks for reporting, @asunar .  I actually wasn't able to get `npm install` to complete at all.  Did you encounter this error, and if so how did you work around it?  https://github.com/TestArmada/boilerplate/issues/4

So far we have mostly been using OSX and Linux with TestArmada, but we'll do our best to support Windows, too.

/cc @Maciek416
