### ISSUE TITLE
Is there any way to execute the same test with different data?

### ISSUE THREAD

**Issue by alfonzjanfrithz** [TestArmada/boilerplate-nightwatch#31]
The current workaround without using magellan is using -c command from nightwatch to specify nightwatch.conf.js.

I had to use some batch script to trigger the test that I want.

```
nightwatch -c sometest.conf.js
nightwatch -c another.conf.js
```

Is there any cleaner way to do it in magellan?

**Comment by Maciek416** [comment]
We're doing it using environment variables that switch between different settings in `dpro` (see project here: https://github.com/TestArmada/dpro ).

For a nightwatch conf-based solution, this (including a command line option) is something that could be implemented within the nightwatch plugin: https://github.com/TestArmada/magellan-nightwatch-plugin
