### ISSUE TITLE
travis.dev:12013/demo-first

### ISSUE THREAD

**Issue by testAccount4325** [TestArmada/boilerplate-nightwatch#58]
![screen shot 2017-06-30 at 12 20 06 am](https://user-images.githubusercontent.com/29681891/27725162-f5051c10-5d29-11e7-949b-78a2115ab4d8.png)

**Comment by archlichking** [comment]
hi @testAccount4325 this boilerplate requires `travis.ci` to point to your `127.0.0.1` in /etc/hosts as documented [here](https://github.com/TestArmada/boilerplate-nightwatch#prerequisites)
