### ISSUE TITLE
first testrun fails

### ISSUE THREAD

**Issue by joelgrimberg** [TestArmada/boilerplate-nightwatch#59]
case:
trying out TestArmada / Boilerplate-nightwatch for the first time:

what did I do:
git clone git@github.com:TestArmada/boilerplate-nightwatch.git
npm install
npm run test:desktop

Log:
09:47:34 [INFO] [Nightwatch Extra] No appium is configured in nightwatch.json, skip appium stop
09:47:34 There was an error while starting the test runner:
09:47:34
09:47:34 Error: listen EADDRNOTAVAIL 127.0.53.53:12013
09:47:34     at Object.exports._errnoException (util.js:1022:11)
09:47:34     at exports._exceptionWithHostPort (util.js:1045:20)
09:47:34     at Server.setupListenHandle [as _listen2] (net.js:1298:19)
09:47:34     at listenInCluster (net.js:1363:12)
09:47:34     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1489:7)
09:47:34     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:96:10)
09:47:34

[INFO] [Magellan]
[INFO] [Magellan] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[INFO] [Magellan] Failed Test: tests/demo-simple.js @env:chrome|executor:local
[INFO] [Magellan]  # attempts: 3
[INFO] [Magellan]      output:
[INFO] [Magellan] 09:47:33 Magellan child process start

--------------
my npm version: 5.x
appium installed (but not configured)

**Comment by archlichking** [comment]
@joelgrimberg you're missing this https://github.com/TestArmada/boilerplate-nightwatch#prerequisites 
```
Also please map travis.dev to 127.0.0.1 in your host file.
```

**Comment by cortezcristian** [comment]
Why do we need that? How can we change the settings if we want to use it locally? Just changing the `launch_url` is enought?
```
conf/nightwatch.json:      "launch_url": "http://travis.dev",
```

**Comment by archlichking** [comment]
@cortezcristian Because this repo is travis enabled for all pull requests and master branch merge verification, and the travis cannot take `localhost`.

And you're right, change https://github.com/TestArmada/boilerplate-nightwatch/blob/master/conf/nightwatch.json#L33 to `localhost` is another way to have test run locally.

**Comment by cortezcristian** [comment]
@archlichking is there a way to run with nightwatch config in parallel? Because adding the following to `conf/nightwatch.json` has no effect, i see this only opens one browser at the time.

```
"test_workers": {
    "enabled": true,
    "workers": "auto"
  },
```

How can I configure this to run each test file in parallel?

**Comment by archlichking** [comment]
@cortezcristian Actually you don't need those configurations. If no `--serial` in the command magellan will run test in parallel with given amount of workers (which is configured as `--max_workers` with default value of 3) by default. 

For example, this magellan command will run demo-web.js in both chrome and firefox at the same time.

```
DPRO=local ./node_modules/.bin/magellan --local_browsers chrome,firefox --test tests/demo-web.js
```

**Comment by RichCrook** [comment]
I have an issue with Chrome trying to make an HTTPS connection locally to travis.dev:

This site can’t provide a secure connection
travis.dev sent an invalid response.

I resolved this by changing: 

`conf/nightwatch.json:      "launch_url": "http://localhost",`

...not sure if this is ideal?

**Comment by archlichking** [comment]
@RichCrook Yes that's the way to solve it. Or you can remove the protocol from`launch_url` and prepend `https` here https://github.com/TestArmada/boilerplate-nightwatch/blob/master/lib/example-base-test-class.js#L51

**Comment by reply2sesh** [comment]
I am running the npm test in my local. Chrome was executed successfully but failing in Firefox. below are the details..

[INFO] [Nightwatch Plugin] Using nightwatch test filter: tests/demo-simple.js
[INFO] [Saucelabs Executor] Connected to sauce without tunnel
[INFO] [Magellan] Running 2 tests with 3 workers with [env:chrome|executor:local, env:firefox|executor:local]
[INFO] [Magellan] --> Worker 2, port range: [12003, 12005], running test: tests/demo-simple.js @env:firefox|executor:local
[INFO] [Magellan] --> Worker 1, port range: [12000, 12002], running test: tests/demo-simple.js @env:chrome|executor:local
[INFO] [Magellan] (1 / 2) <-- Worker 1 PASS  tests/demo-simple.js @env:chrome|executor:local 
[INFO] [Magellan] (2 / 2) <-- Worker 2 FAIL (will retry).  Spent 61421 msec tests/demo-simple.js @env:firefox|executor:local 
[INFO] [Magellan] --> Worker 1, port range: [12006, 12008], running test: tests/demo-simple.js @env:firefox|executor:local
[INFO] [Magellan] (2 / 2) <-- Worker 1 FAIL (will retry).  Spent 61695 msec tests/demo-simple.js @env:firefox|executor:local 
[INFO] [Magellan] --> Worker 1, port range: [12009, 12011], running test: tests/demo-simple.js @env:firefox|executor:local
[INFO] [Magellan] (2 / 2) <-- Worker 1 FAIL  tests/demo-simple.js @env:firefox|executor:local 
[INFO] [Magellan] ============= Failed Tests:  =============
[INFO] [Magellan] - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[INFO] [Magellan] Failed Test: tests/demo-simple.js @env:firefox|executor:local
[INFO] [Magellan]  # attempts: 3
[INFO] [Magellan]      output: 
[INFO] [Magellan] 15:00:12 Magellan child process start

15:00:12 [INFO] [Nightwatch Extra] nightwatch-magellan has found nightwatch configuration at /Users/srbomma/testArmada/boilerplate-nightwatch/temp/build-magellan-1d488e5453b369_5af065775ab27__temp_assets/nightwatch.json
15:00:12 [INFO] [Nightwatch Extra] No appium is configured in nightwatch.json, skip appium start
15:00:12 Starting selenium server... 
15:00:13 started - PID:  73883
15:00:13 [Demo Simple] Test Suite
15:00:13 ============================
15:00:13 starting drydock 0.4.4 server on localhost:12010...
15:00:13 (node:73882) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
15:00:13 Running:  Load demo page
15:01:13 Error retrieving a new session from the selenium server
15:01:13 [INFO] [Nightwatch Extra] No appium is configured in nightwatch.json, skip appium stop
15:01:13 Connection refused! Is selenium server started?
15:01:13 
15:01:13 { Error: socket hang up
15:01:13     at createHangUpError (_http_client.js:302:15)
15:01:13     at Socket.socketCloseListener (_http_client.js:334:23)
15:01:13     at emitOne (events.js:101:20)
15:01:13     at Socket.emit (events.js:191:7)
15:01:13     at TCP._handle.close [as _onclose] (net.js:509:12) code: 'ECONNRESET' }

[INFO] [Magellan] 
[INFO] [Magellan] ============= Suite Complete =============
[INFO] [Magellan]      Status: FAILED
[INFO] [Magellan]     Runtime: 3m 13.5s
[INFO] [Magellan] Total tests: 2
[INFO] [Magellan]  Successful: 1 / 2
[INFO] [Magellan]      Failed: 1 / 2
npm ERR! Test failed.  See above for more details.
