### ISSUE TITLE
Testrunner.js of testarmada-magellan is giving incorrect test case count.

### ISSUE THREAD

**Issue by Rajesh-Narayanappa87** [TestArmada/boilerplate-nightwatch#68]
We an have 2 testcase in single file. Like below:

```
module.exports = new Test({
  tags: ["pageobject", "web", "home"],

  "Homepage/Rajesh/c12345/ValidateHomepage": function(client) {
    client.url('https://flipkart.com');
    client.end();
  },
  "Homepage/Rajesh/c12345/validateGooglePage": function(client) {
    client.url('https://google.com');
    client.end();
}
});
```
testrunner.js under testarmada-magellan give "numTests" as 1 where as nightwatch gives 2(correct one).
I tried with "testarmada-magellan-json-reporter" . Json reporter also gives total tests as 1 and testcase name is incorrect too. It has file name instead of testcase name.

**Comment by Rajesh-Narayanappa87** [comment]
Is this still active group?? Can you pls respond

**Comment by archlichking** [comment]
@Rajesh-Narayanappa87 Magellan counts test amount by .js files. In your case 1 is expected.
