### ISSUE TITLE
'DPRO' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by spnraju** [TestArmada/boilerplate-nightwatch#74]
Hello!

Thank you for the great work!

I have cloned this repo and did a npm i. But I am getting below error when i try to run any tests.

'DPRO' is not recognized as an internal or external command,
operable program or batch file.

What am i missing here?

**Comment by ankititp** [comment]
me too facing this issue ?Can anyone Please help

**Comment by spnraju** [comment]
@ankititp any luck with the issue?

**Comment by ankititp** [comment]
No , still facing same issue :(

**Comment by spnraju** [comment]
@archlichking Could you kindly help?

**Comment by archlichking** [comment]
are you on windows? did you follow https://github.com/TestArmada/boilerplate-nightwatch#run ?

**Comment by spnraju** [comment]
thanks @archlichking , I don't get that error now. But keeping this open until i am able to run the tests in my localhost successfully.
